# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Check format with black
      run: |
        poetry run task format-check 
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run task lint-flake8 
    - name: Lint
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run task lint 
    - name: Test with pytest
      run: |
        poetry run task test | true
    - name: launch the application
      run: |
        poetry run task discover --help

